### ISSUE TITLE
Unable to achieve single molecule image

### ISSUE THREAD

**Issue by TheGreatFox** [ProkopHapala/ProbeParticleModel#5]
I am running into an issue to replicate the results of the online version of this software. Which branch of PPM actually utilizes autogeom to shrink the boundaries if I only want to focus on a single molecule (such as DBP)? I can achieve this using the online version, but after running through the different branches (master, dev, OpenCL), none seem to respect the PBC option in the same way. Should I be building my own script based on testServer2.py?

**Comment by ProkopHapala** [comment]
Hello, 
the version on the web is very old. Exactly as you say, on web "autogeom" is used which shifts the geometry so that you automatically scan in relevant distance. After discussion with colleagues we removed it form newer version because it was confusing. Although I find "autogeom" nice for inexperienced user, I agree with colleagues that for experienced users it rather limits and distracts control you have. Also shifted geometry it is not compactible with Hatree potential from DFT calculation.
   
What exactly you want to achieve? I guess simplest would be just to move geometry manually and set the cell size accordingly. Or you can also call `PPU.autogeom()` in generateLJFF.py and in generateElFF.py just after `PPH.parseAtoms()` ... (I guess it should work, but I did not tested now)

you are right that testServer2.py corresponds to the script which is used on the web ... but it is not maintained so I'm not sure it works with current version of PP code.

**Comment by TheGreatFox** [comment]
Thanks for the reply (apologies for the delay). I was able to find the function and was able to correctly write a solution. The autogeom function still behaves correctly in most situations, but just wasn't implemented correctly in the example scripts for the new codebase. I was adapting this software for some projects. Thanks for the assistance.
