### ISSUE TITLE
for the stiffness of Pt tip

### ISSUE THREAD

**Issue by Msunshinep** [ProkopHapala/ProbeParticleModel#7]
Hi!

I want to do some simulation with the Pt-tip, just a Pt metal tip，how do you think about the stiffness of the Pt-tip, how much you think is appropriate？

**Comment by ProkopHapala** [comment]
Hi, I don't think ProbeParticleModel is suitable for that. 

Pt is not inert (there may be some chemical interaction with sample) so the potential used in ProbeParticleModel are not suable. Also we don't have reasonable van der Waals parameters for metals. The main strength of  ProbeParticleModel  is to reproduce effects of CO bending, but with metalic tip which is order of magnitude stiffer ( K~10-20 N/m for metalic tip rather than 0.2-0.5 N/m for CO ) there will be no bending effects.

**Comment by Msunshinep** [comment]
Thank you for your detailed reply. 
You don't think ProbeParticleModel is suitable for that,
1.(Pt is not inert--there may be some chemical interaction with sample) so the potential used in ProbeParticleModel are not suable)  How about the tip hight is not so near(may be the afm signal is just appear, and not so strong) do you think this chemical interaction can be  neglected, and this Model can be used?
2.(For the reasonable van der Waals parameters for metals) I see that in your atomtype, there are some parameters for metals like Pt(2.37    0.01) , the reference is (Req is taken from: Batsanov, S. S.,   Van der Waals Radii of Elements,  Inorganic Materials, 2001,  Vol 37, PP 871-885, Nr. 9) which gives the Van der Waals Radii, this Van der Waals Radii 2.37 is not well ? or you mean the 0.01 is not accurate?

**Comment by Msunshinep** [comment]
> Hi, I don't think ProbeParticleModel is suitable for that.
> 
> Pt is not inert (there may be some chemical interaction with sample) so the potential used in ProbeParticleModel are not suable. Also we don't have reasonable van der Waals parameters for metals. The main strength of ProbeParticleModel is to reproduce effects of CO bending, but with metalic tip which is order of magnitude stiffer ( K~10-20 N/m for metalic tip rather than 0.2-0.5 N/m for CO ) there will be no bending effects.


Thank you for your detailed reply.
You don't think ProbeParticleModel is suitable for that,
1.(Pt is not inert--there may be some chemical interaction with sample) so the potential used in ProbeParticleModel are not suable) How about the tip hight is not so near(may be the afm signal is just appear, and not so strong) do you think this chemical interaction can be neglected, and this Model can be used?
2.(For the reasonable van der Waals parameters for metals) I see that in your atomtype, there are some parameters for metals like Pt(2.37 0.01) , the reference is (Req is taken from: Batsanov, S. S., Van der Waals Radii of Elements, Inorganic Materials, 2001, Vol 37, PP 871-885, Nr. 9) which gives the Van der Waals Radii, this Van der Waals Radii 2.37 is not well ? or you mean the 0.01 is not accurate?

**Comment by ProkopHapala** [comment]
Hi, 

1) If you are in far-distance regime (not in contact) with metallic tip than interaction should not be approximated by single apex atom, since it depends on whole structure of tip apex (more atoms).  Do you know  (Smoluchowski-effect) ( nice disscussion e.g. here https://arxiv.org/pdf/1402.5246v1.pdf ).  

Are you able to obtain atomic resolution in this regime?

You can perhaps still try to simulate that Smoluchowski dipole in ProbeParticleModel by adding some dipole when you generate the electrostatic forcefield ( python $PPPATH/generateElFF.py -i LOCPOT.xsf --tip pz ; see e.g. https://github.com/ProkopHapala/ProbeParticleModel/blob/master/examples/PTCDA_Hartree_dz2/run.sh ) ... but I have not idea about the magnitude of that dipole, and still I think ProbeParticleModel is perhaps not optimal tool for that kind of simulation.

2) Yes, that Batsanov, S. S. paper gives vdW radius, but does not give vdW energy (so the number 0.01eV is rather just a guess and placeholder ). But even  vdW radius can differ from tip to tip depending on bonds to surrounding atoms  - polarizability of metals is non-local property.
